// <auto-generated />
using System;
using DotNetAcademy.BikeShop.Host.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetAcademy.BikeShop.Host.Migrations
{
    [DbContext(typeof(BikeShopDbContext))]
    [Migration("20201028103457_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "xbql52za",
                            Price = 257.7m
                        },
                        new
                        {
                            Id = 2,
                            Name = "0bbo104h",
                            Price = 207.32m
                        },
                        new
                        {
                            Id = 3,
                            Name = "pagvzybw",
                            Price = 31.41m
                        },
                        new
                        {
                            Id = 4,
                            Name = "1tdsvfre",
                            Price = 396.52m
                        },
                        new
                        {
                            Id = 5,
                            Name = "3wwjr5af",
                            Price = 162.73m
                        },
                        new
                        {
                            Id = 6,
                            Name = "rx5a5uif",
                            Price = 357.42m
                        },
                        new
                        {
                            Id = 7,
                            Name = "n4idaifn",
                            Price = 124.46m
                        },
                        new
                        {
                            Id = 8,
                            Name = "lyecnqyz",
                            Price = 183.41m
                        },
                        new
                        {
                            Id = 9,
                            Name = "hydcj3pq",
                            Price = 95.63m
                        },
                        new
                        {
                            Id = 10,
                            Name = "55mkjfza",
                            Price = 169.94m
                        },
                        new
                        {
                            Id = 11,
                            Name = "kgjwdpiz",
                            Price = 324.1m
                        },
                        new
                        {
                            Id = 12,
                            Name = "r3fyde4u",
                            Price = 255.12m
                        },
                        new
                        {
                            Id = 13,
                            Name = "ee5hai2b",
                            Price = 390.12m
                        },
                        new
                        {
                            Id = 14,
                            Name = "suc20vqk",
                            Price = 269.78m
                        },
                        new
                        {
                            Id = 15,
                            Name = "go3pvt45",
                            Price = 453.02m
                        },
                        new
                        {
                            Id = 16,
                            Name = "uwsz0ktz",
                            Price = 383.34m
                        },
                        new
                        {
                            Id = 17,
                            Name = "utfsrazf",
                            Price = 356.02m
                        },
                        new
                        {
                            Id = 18,
                            Name = "nd1muem2",
                            Price = 474.36m
                        },
                        new
                        {
                            Id = 19,
                            Name = "i3gj0fzs",
                            Price = 304.66m
                        },
                        new
                        {
                            Id = 20,
                            Name = "qyc3zcrc",
                            Price = 341.16m
                        },
                        new
                        {
                            Id = 21,
                            Name = "hik15flb",
                            Price = 72.49m
                        },
                        new
                        {
                            Id = 22,
                            Name = "otbqpwrp",
                            Price = 115.86m
                        },
                        new
                        {
                            Id = 23,
                            Name = "cfvlclvx",
                            Price = 137.22m
                        },
                        new
                        {
                            Id = 24,
                            Name = "wakpcogx",
                            Price = 218.07m
                        },
                        new
                        {
                            Id = 25,
                            Name = "hbwa4cg4",
                            Price = 209.12m
                        },
                        new
                        {
                            Id = 26,
                            Name = "jvtteamk",
                            Price = 377.98m
                        },
                        new
                        {
                            Id = 27,
                            Name = "0jhkjvwf",
                            Price = 496.52m
                        },
                        new
                        {
                            Id = 28,
                            Name = "4ar4pm5y",
                            Price = 432.69m
                        },
                        new
                        {
                            Id = 29,
                            Name = "xp0nsutm",
                            Price = 335.38m
                        },
                        new
                        {
                            Id = 30,
                            Name = "oyuwdc2c",
                            Price = 288.07m
                        },
                        new
                        {
                            Id = 31,
                            Name = "1b0bqwds",
                            Price = 307.34m
                        },
                        new
                        {
                            Id = 32,
                            Name = "aaixrj10",
                            Price = 139.9m
                        },
                        new
                        {
                            Id = 33,
                            Name = "mzdxoaom",
                            Price = 496.67m
                        },
                        new
                        {
                            Id = 34,
                            Name = "zzj3nhg1",
                            Price = 473.94m
                        },
                        new
                        {
                            Id = 35,
                            Name = "4tbk5iwp",
                            Price = 53.02m
                        },
                        new
                        {
                            Id = 36,
                            Name = "1bqs3bu1",
                            Price = 457.35m
                        },
                        new
                        {
                            Id = 37,
                            Name = "2u0ex4rl",
                            Price = 488.16m
                        },
                        new
                        {
                            Id = 38,
                            Name = "y4ityerx",
                            Price = 490.01m
                        },
                        new
                        {
                            Id = 39,
                            Name = "1xfl5ouv",
                            Price = 323.58m
                        },
                        new
                        {
                            Id = 40,
                            Name = "m05xhabz",
                            Price = 320.71m
                        },
                        new
                        {
                            Id = 41,
                            Name = "00dneyy1",
                            Price = 174.83m
                        },
                        new
                        {
                            Id = 42,
                            Name = "lizyqna5",
                            Price = 309.85m
                        },
                        new
                        {
                            Id = 43,
                            Name = "z1puc4u4",
                            Price = 180.76m
                        },
                        new
                        {
                            Id = 44,
                            Name = "vprqaj5u",
                            Price = 328.04m
                        },
                        new
                        {
                            Id = 45,
                            Name = "1kbtooes",
                            Price = 421.96m
                        },
                        new
                        {
                            Id = 46,
                            Name = "ksu5hvo3",
                            Price = 31.27m
                        },
                        new
                        {
                            Id = 47,
                            Name = "glwj0y5b",
                            Price = 241.99m
                        },
                        new
                        {
                            Id = 48,
                            Name = "otjm3keg",
                            Price = 26.6m
                        },
                        new
                        {
                            Id = 49,
                            Name = "hipnup04",
                            Price = 417.38m
                        },
                        new
                        {
                            Id = 50,
                            Name = "sbwv2mro",
                            Price = 471.6m
                        });
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.ShoppingBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ShoppingBags");
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BagId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingItems");
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.ShoppingBag", b =>
                {
                    b.HasOne("DotNetAcademy.BikeShop.Host.Models.Customer", "Customer")
                        .WithMany("Bags")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.ShoppingItem", b =>
                {
                    b.HasOne("DotNetAcademy.BikeShop.Host.Models.ShoppingBag", "Bag")
                        .WithMany("Items")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetAcademy.BikeShop.Host.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
