// <auto-generated />
using System;
using DotNetAcademy.BikeShop.Host.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetAcademy.BikeShop.Host.Migrations
{
    [DbContext(typeof(BikeShopDbContext))]
    partial class BikeShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "vc1uznwj",
                            Price = 40.590000000000003
                        },
                        new
                        {
                            Id = 2,
                            Name = "mdaadqg1",
                            Price = 229.09999999999999
                        },
                        new
                        {
                            Id = 3,
                            Name = "ff3sibmb",
                            Price = 179.69
                        },
                        new
                        {
                            Id = 4,
                            Name = "zdkipmp2",
                            Price = 272.33999999999997
                        },
                        new
                        {
                            Id = 5,
                            Name = "gxq1n5s0",
                            Price = 161.96000000000001
                        },
                        new
                        {
                            Id = 6,
                            Name = "mivlqwgh",
                            Price = 157.28
                        },
                        new
                        {
                            Id = 7,
                            Name = "dw30tqds",
                            Price = 244.31
                        },
                        new
                        {
                            Id = 8,
                            Name = "cbnrerlc",
                            Price = 499.83999999999997
                        },
                        new
                        {
                            Id = 9,
                            Name = "jtkyz5wh",
                            Price = 137.94999999999999
                        },
                        new
                        {
                            Id = 10,
                            Name = "ghr42jq2",
                            Price = 128.88999999999999
                        },
                        new
                        {
                            Id = 11,
                            Name = "3rhl5bq1",
                            Price = 358.39999999999998
                        },
                        new
                        {
                            Id = 12,
                            Name = "t232fevx",
                            Price = 399.64999999999998
                        },
                        new
                        {
                            Id = 13,
                            Name = "0ichobhe",
                            Price = 476.87
                        },
                        new
                        {
                            Id = 14,
                            Name = "hvlg3eu5",
                            Price = 133.91999999999999
                        },
                        new
                        {
                            Id = 15,
                            Name = "q2k1yflt",
                            Price = 331.06999999999999
                        },
                        new
                        {
                            Id = 16,
                            Name = "uzufu2rn",
                            Price = 126.41
                        },
                        new
                        {
                            Id = 17,
                            Name = "awlazzkz",
                            Price = 262.20999999999998
                        },
                        new
                        {
                            Id = 18,
                            Name = "ib0qujcg",
                            Price = 281.54000000000002
                        },
                        new
                        {
                            Id = 19,
                            Name = "ukub40lq",
                            Price = 486.72000000000003
                        },
                        new
                        {
                            Id = 20,
                            Name = "twol4hdq",
                            Price = 412.26999999999998
                        },
                        new
                        {
                            Id = 21,
                            Name = "fptbv22u",
                            Price = 83.010000000000005
                        },
                        new
                        {
                            Id = 22,
                            Name = "e3130zht",
                            Price = 29.210000000000001
                        },
                        new
                        {
                            Id = 23,
                            Name = "45clrq1h",
                            Price = 318.76999999999998
                        },
                        new
                        {
                            Id = 24,
                            Name = "110t354x",
                            Price = 222.34
                        },
                        new
                        {
                            Id = 25,
                            Name = "gbay0meh",
                            Price = 139.44999999999999
                        },
                        new
                        {
                            Id = 26,
                            Name = "unxphj0f",
                            Price = 246.25999999999999
                        },
                        new
                        {
                            Id = 27,
                            Name = "fs0efory",
                            Price = 141.15000000000001
                        },
                        new
                        {
                            Id = 28,
                            Name = "di1qix5p",
                            Price = 309.66000000000003
                        },
                        new
                        {
                            Id = 29,
                            Name = "weh4aaav",
                            Price = 489.56999999999999
                        },
                        new
                        {
                            Id = 30,
                            Name = "zwkoni0w",
                            Price = 60.340000000000003
                        },
                        new
                        {
                            Id = 31,
                            Name = "s3kq5w1q",
                            Price = 312.86000000000001
                        },
                        new
                        {
                            Id = 32,
                            Name = "om4uv233",
                            Price = 306.39999999999998
                        },
                        new
                        {
                            Id = 33,
                            Name = "qr3alxeb",
                            Price = 433.72000000000003
                        },
                        new
                        {
                            Id = 34,
                            Name = "so1vrlbh",
                            Price = 467.83999999999997
                        },
                        new
                        {
                            Id = 35,
                            Name = "hryalvvv",
                            Price = 349.55000000000001
                        },
                        new
                        {
                            Id = 36,
                            Name = "m0vz2ji5",
                            Price = 286.31999999999999
                        },
                        new
                        {
                            Id = 37,
                            Name = "3ftp1ejt",
                            Price = 57.549999999999997
                        },
                        new
                        {
                            Id = 38,
                            Name = "er5lg1sk",
                            Price = 18.199999999999999
                        },
                        new
                        {
                            Id = 39,
                            Name = "saiafcgo",
                            Price = 299.38999999999999
                        },
                        new
                        {
                            Id = 40,
                            Name = "3hcy4htn",
                            Price = 417.86000000000001
                        },
                        new
                        {
                            Id = 41,
                            Name = "yof2nwyx",
                            Price = 349.62
                        },
                        new
                        {
                            Id = 42,
                            Name = "ndwanyti",
                            Price = 388.89999999999998
                        },
                        new
                        {
                            Id = 43,
                            Name = "ztkii2th",
                            Price = 434.04000000000002
                        },
                        new
                        {
                            Id = 44,
                            Name = "jeaddo0u",
                            Price = 464.94999999999999
                        },
                        new
                        {
                            Id = 45,
                            Name = "xy2njrkb",
                            Price = 62.619999999999997
                        },
                        new
                        {
                            Id = 46,
                            Name = "jf0ogs4q",
                            Price = 342.17000000000002
                        },
                        new
                        {
                            Id = 47,
                            Name = "sanokmgl",
                            Price = 452.55000000000001
                        },
                        new
                        {
                            Id = 48,
                            Name = "sivb41u3",
                            Price = 484.86000000000001
                        },
                        new
                        {
                            Id = 49,
                            Name = "4lmaqmxu",
                            Price = 383.44
                        },
                        new
                        {
                            Id = 50,
                            Name = "ig01xcc5",
                            Price = 54.600000000000001
                        });
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.ShoppingBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ShoppingBags");
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BagId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingItems");
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.ShoppingBag", b =>
                {
                    b.HasOne("DotNetAcademy.BikeShop.Host.Models.Customer", "Customer")
                        .WithMany("Bags")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNetAcademy.BikeShop.Host.Models.ShoppingItem", b =>
                {
                    b.HasOne("DotNetAcademy.BikeShop.Host.Models.ShoppingBag", "Bag")
                        .WithMany("Items")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetAcademy.BikeShop.Host.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
